---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-hub
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: hub-agent
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: traefik-hub
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      name: ghcr.io/traefik/hub-agent-kubernetes
      tag: experimental
      pullPolicy: always
    token: "${SECRET_TRAEFIK_HUB_TOKEN}"
    podAnnotations:
      secret.reloader.stakater.com/reload: "traefik-hub-secrets"
  postBuild:
    substituteFrom:
      - kind: Secret
        name: traefik-hub-secrets
