# yamllint disable
apiVersion: v1
data:
    credential.json: ENC[AES256_GCM,data:8y/gRVgJ22ARE8buacsE+uZT8swcIEsQcxYq6/qs758CEyND9RGYC5RHVSqVsQU5Yf3h9XbFOL2ntepEYbojg1Ij/Jsm/k4mT6h5dbiDjukTEC1htIFON8/35oUfEl4875Wh3Kb+REqVg++ThwAY+rcUN3Nx5N65w4kPKON045UeTmX879Hl2XTnbB3VZriaOha51PI7pozXSPbT1jHOmQaBTWd72IgfF7u5cgFIUp7icYCs2slVgphF86SoOetRonwvh6zW8FUbkZvfgj1BWyVJkysdDnNak3U/W1aLcFpyffu23NEq4EKDeEOypOik/pHJPny7ND6mH6vhXr5Q4TqbVHamO/5g0UxSsZZf9ZmyN3812Ql2KzBDsKv1jfPju9a12/tWMXa5qsIdae1cDA==,iv:JW2pQ0xRkdo6E15h/p2SYVhgmMuOHAYfEApOvFlJ4sw=,tag:7vSVph4f+8vf+q4Rf8h4+A==,type:str]
    credentials.json: ENC[AES256_GCM,data:0MgLYSzzOPDb47dbhV8uPs/WENztpF0Z7riHmWbN/gis4WsRWDuNpjp5jxVN8lz5Q54ApeIBhjhsjFyY1ROKAZFsUuzKRTyomY9+EX6/eRXrvzHAxfhts5cSE7NkX7Iqh7Zx3ZC3KtSJyF364Cl0L4cLyOV5a1NSNEqWoI/GMhpxNP9ZJeAufpbkoiAt0vSNLfnw9lQqHPZ4oiyVL6TCgTZM55RQRMOi7Qpt7M5foqsJYEpKxM2GKsMra6pIj0UAYybmyMvo44kOGWwruhO5l1MobJQYpq08UXtD10dGVsVIGOZLhUisnRgLEgXmyNlimbcI5zEs70LI99J7F6T8Q417Dy5pXC1Fo4iv95P/1ce0CdoDurEOEZLRlKqDDNkLNhh6FCUSBYchvuANO21fCQ==,iv:eUXlD+C3wC/JL/aCVcdk3ydX4dVFhui2GrZoW6yOQ1U=,tag:KrxPf0BwjSZvUFvYQe+rvg==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2022-07-01T06:51:50Z"
    name: cloudflared-credentials
    namespace: networking
    resourceVersion: "51030905"
    uid: c591f8ba-dd93-443e-a354-aaacb9c122bd
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-01T06:55:48Z"
    mac: ENC[AES256_GCM,data:z4yBjCELkqjUjzSqp537tq/kD642TZ4VZDb6h5T74RT54+dzBtcKfVjcb3gWB+d03rYDT2N9QToBOpNfIn1SCVjPpPMQqCF+GBWL+QDGug7DH266T6y5g4UklM4e4AYi4Dh4F0pAq1KN6tH7GCVK7jloI/Xh30fo/PvLVX8VpvY=,iv:ZBmo0ipPeW/6QwOu1WlPAi0z32OYJvitxyCGK3lAFRw=,tag:n8q5zHv4aaWLLE71lS0eYw==,type:str]
    pgp:
        - created_at: "2022-07-01T06:55:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WAQ/8DloLtdyEaWlN7jOYeNNCfKXxsprBhGWDcfzsrbLmbVKN
            OUznz9KJmIdjbaDNc097SJB/fMg3VMg56R/nGJSdExbTbozgxObD8esteXd28lgI
            f56U2faSzHdWsXvdykrkXFrQ7UDcTEEwHiGmLDRSel77Vkt0NhP3gW5mYDFH86bV
            E/o2BV31QLM6tifL2ca8ghISdV6UFvm3swoMDd+QPXcIYNzfJv/LR5RgdhN78Pe8
            O+4Ug10wJvEB13VhOw3uamQ/C4sCY/H/+t4POvv47vQdTU/bJ3QE1++NzaSimaUA
            TqZpXKyi5cvQQqDbF8bXbCS6lqRIjxzBNC0rbZ2I0MuVd9rhEHW2t0o4pnX4bIo/
            3utNuGWSZVJszh6LaOdXK/7BaUvQHG5er0R/FRBATlRq47etGSGMqZ68W7zf1ZBw
            kJdjv7uP3IveMGURwb0djfW5IIUmq3GcsiRp0XvZeP09tcdED1qgdnPO5utnMjmz
            GBNcp339hjuOBT5EApr5x+uwVrMX1mcrMVOv/JviKo10eGmnR8cI2nZfN07dDjy1
            Rbu+1JFT5jgpo1MNZq0gffs8nPc6Y+VROc5OG2ySdUE3N3CV7WDmGD7iuE9DxVfo
            PeDajFVbZNW12duzybIyijg8MkUNhgLz5bqb1FrmYAo7sZUifautc67mqR76wTzU
            ZgEJAhDKiDd7H4PihLxDfMjr2Nb9BXfh7i64PLDWkDuqblj8FfM9SAls4I5rQW8b
            8TNTnJAcfSKoB5fRPaSBlrpoerKgXn1ys14p3Tzq9ubqx6VDew5c2ovvlTosLWOU
            y7Atbj+HZw==
            =/2fS
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2022-07-01T06:55:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6AQ//SetstCT5dQRozQpJ/fdH/ToQcnnI/oB0Dzt5YuOLp4Qq
            Ceev6jNbG904ziCif3FoJ4iyI/BGhl0eeZVzkDGp40lb23n8ze1Up3+KGN3J4gyU
            uQ4m/kD5Hd2VksRITNldM10RNWG9PY8fzh7Ej2LO15fTKFz3JX4UC0xclXIzP9kx
            HJW4QvfDIY75/JylstADFN+VUEJ0mjyGh9w4eBxOypb8wYTB0ykOm95zYBy1RCIs
            raR3Q61WZjHLKrQW5Ltd9/0baPobD2WhQY3DxaADgpdeLLumqx4VqsntYpKKl+Dt
            8hu3BIJ6MDwXK8LKhZuk9qxKMQIrWytZkJk3/9jcKerWJ2Ugwu86QT6x9Oo3x7w6
            lwLPyT0enP+Xg4tF6+W3y0u3YeibajgrtSr5xaKYJ7nfeDX9KjarCmO+a1wWLSAm
            Zqlg89qjNfNe7uZi51hLa0BzlOvKNQqpZoT2FHfaZu4she/KVaXoD7JJQIufcswH
            UEgkLKgaGuAzYa9lDYPdzA9XJp/J34hMHO/vLeenPvMcnTpJe4VC6SDRjv0yjeMk
            qYk53Q+jYBhyF6wxRQMoY9XXKSFO5JXmhfq14ot/dHdquEu2iGsvEUvR6K1wvBWR
            1+yxLCNsuXa9J/9S/zV+j0LCJIhdIE/vh+M75Gjnir9lkqFEP3q0xqCjVPFhISPU
            ZgEJAhDZ/6dfkJC5eKB8qbrSEd2oxDGXh7ds3h0Ch3UCBPPjRpyfNsT4DAmKBdMX
            8mfRU5LgQzK7JuS8uzM1aJiyalnM/K660fYTN8P/GiJtKV16jhBqRTTfkDhAMJQL
            89kZ/TCbaw==
            =x7PX
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
