---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"
  KUBE_CONFIG_PATH: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  cluster: .taskfiles/ClusterTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
  kubectl: .taskfiles/kubectl.yml
  flux: .taskfiles/flux.yml
  format: .taskfiles/format.yml
  lint: .taskfiles/lint.yml
  pre-commit: .taskfiles/pre-commit.yml
