---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: khuedoan-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    image:
      repository: docker.io/raspbernetes/cloudflared
      tag: "2022.3.2"
    credentials:
      existingSecret: cloudflared-credentials
    config:
      tunnel: tunnel
      ingress:
        - hostname: "test.${SECRET_DOMAIN}"
          service: hello_world
          originRequest:
            noTLSVerify: true
        - hostname: "*.${SECRET_DOMAIN}"
          service: "https://traefik.networking.svc.cluster.local"
          originRequest:
            noTLSVerify: true
        - service: http_status:404
