---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: khuedoan
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1
    image:
      repository: docker.io/raspbernetes/cloudflared
      tag: "2022.6.3"
    credentials:
      existingSecret: cloudflared-credentials
    config:
      tunnel: homelab-tunnel
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: https://traefik.networking.svc.cluster.local
          originRequest:
            noTLSVerify: true
        - service: http_status:404
    podAnnotations:
      secret.reloader.stakater.com/reload: "cloudflared-credentials"
