# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
stringData:
    credentials.json: ENC[AES256_GCM,data:3N2NWe72tvdg0KE6IztQVKbfjxj8iohqU9GhKdJpZsl1qh5FaZhU5vM4slSiMIOt1VOBsupD6qV+FykSzGQAxbwANiVD86dCPiwo0mPRwAbSHUzuwjEepqxkJp/uU8v684Ciwy5f5rYrqGI7U2Gcg6kxkv7rAOKHP//ysork5Vay5Y3VRR33tl2dfXjU7YVibTmVMhby5TBddbepMTMFT0hQUB/t6zkzwejwEDSFLzI/2v/vOAedRngFdEHMNas=,iv:s/3AzFIZ3RvuDRAZdqThEP41UKX73R4DrYcSQ9jsIeE=,tag:dROeXqK2MgZgjxT0+kBrkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-23T19:28:53Z"
    mac: ENC[AES256_GCM,data:GwKX1gN6iLJqwxclYqgJRFdOtpM6KjYFHfLv4gscWGgjOEvGqIGxNHh4LTuM18/BLdd3VYkyWoc2y7W+YDYmj7tFDZxzedvbXYYoDDKYUQO78qv8vuiuCACEM3Azt9YvphlITsn8EXfTsNwBah1CjHHV83LlAh0196DYuux1/Ko=,iv:rycqy4UK5SIM0NNCCoN38VGbv4pqoX+Ss3LgXBTzCuw=,tag:Z1s7Zurwcmnh5k54SUC0Fg==,type:str]
    pgp:
        - created_at: "2021-10-30T04:39:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WAQ//fM6LYf0qVFWGfoite9IY+OJyxd/bwpDAGv+MwOmFvDxw
            vZsBSgQtWlZYwnOGbZBqxUWHrdoZCI0PGZogeZWmrWWRnxQVeyYul0A7AW7YKOnI
            kY/KAJ0+ypFrS/rc0+yTOgWVHAut1Y30wS0iAGuZAlaFJGELPLrm4d6C36nSiGd2
            e9uFjQjOBBbuXzg5q3gIe6eXRt4VmAtIpdDe/OfGYO1BFhShiE8k3DJdy7wjWTf3
            6JaNMQDSTc9bpkJ/H9lcx7upbn/JKYJ6VoEE1ZyCTlTXa0dViJEmv/zFmx86HYCr
            i2oj+97+RS0mvPHqPtTfiUlbMt5MRcAO7hdi8QtZLwj8dejnlG3EiF5HrZZNIslX
            RM2fCDjLVuoa9wHs3fIDHwJtQe73DeJaoqSN26MfGfgnCrb2Icl3PbIfvjMZcBKq
            5An6LhtiLicVXJFFDaIKlKc9Y8s2Ic2H4AVbU0d+/dyQ43M781GG/1vgm8OXoyU5
            gfigI6FyZYv490sfOnreSo24dxTyo8341gdC9Pshc5/MCxaQNOKjh/0NnMRwF8sv
            UsTDTduSvdSTivZ9DH48gYCHOs/hHF9fFyeo8nKWeDZLMSsNqm6WOlEv7olykRzM
            QD3th/PL6zTo2CtgEw7cwjKXv559Isl51A3jk8u4CG+Z1UdlhaHRSKyX0ZvRy9/U
            aAEJAhA6ivb+E/cjIcXGDWYZl3uUE3vV0pXu7nW0xA2PU+9h0U0w4S7Ly54OW4gM
            NkqT9bskxain5lgwj7ieaPPxfEhNU8JHN5lOo0Z/LjhESybxgHpu9BP5rqozg/XO
            vl98gEfD+v7K
            =tsIh
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2021-10-30T04:39:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6AQ/8CSyefF97y1eqtg31k5I9LeHkOdpacsHrxmdEC8+btYGe
            oW4Y5CJPnhw85zL9BgNO71ad+NCRGScM4lz0tnTeJ+UXpYFzGBaB0NJZoh3P04DW
            2lDNWEVekDwTVaQfURL/jYkPVBpm2FSX5y3q5JCqFnHKRUMqbCnmMf3l5FIzsEgg
            XPdArPZ47M4iOnSzp3XcfzldyVXViMsosbWgoFaWqO1QCPvId0q4IeMBwn8IT3Ep
            LODiisccPgDQmzY6CESBssxjnMQsZ+BfyoGeJMJMXTn6Ywv0jCMWSzehi+H8Yxrh
            H4k66hTyrY0r2kycTkZ5/IUuESqJ/xlNufh17podjL8TO82Fz+PyFHjpD10eWsL8
            ewdU1kljZ8f9d38l7sUg6Puha/O5XGgBeR6iS3Q3B7Je/zwSsWr8ywlcNJYmuPjW
            GQ6cbdUCaH2DmSw8ROePn+0kdaLX0YV/s4CIGaktyw89Byx/FT+N6FaFpVTrmpny
            PYxAeMAGwiZXEVBttXIJjh9mBx/j5+02bK9k76kFjjCSFt9Abha33F11ovv/ljW0
            uFjjVIyKnor6HP+G2NgB4bw2IdF93AEa/nkOIcO6DEFhlDKYk8+FZaVjdqDP63nv
            WyxashQpmkEwg0/xjNxLcVVwM4I++q0dWcew3g2IUIWE8ud5nEJLEwQLx1+nsmLU
            aAEJAhDc8umY47Y0DIbkKPbmV8FICsRVMee9Ykor7uuVILU2BI+uxfTt/BBG1z7+
            tHuLqkc0L+t/NmMHeODFZUB1UVeXh2imVL617DMvyySkPb70n0qtMG/sCBBsJZp+
            cNF76XzSgxiu
            =ryvs
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
