---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    recommender:
      enabled: true
    updater:
      enabled: false
    admissionController:
      enabled: false
