---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: polaris
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: quay.io/fairwinds/polaris
      tag: "7.0"
    dashboard:
      enable: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          # certs
          cert-manager.io/cluster-issuer: "letsencrypt-production"

          # Hostname
          coredns.io/hostname: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"

          # Hajimari
          hajimari.io/enable: "true"
          hajimari.io/icon: "flare"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-tls"
