# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-ddns
    namespace: networking
stringData:
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:38LmeWTaE5KzJ0Q60iUymZneK5AIGOo3pK0MLaYy3MJmXshGb1695w==,iv:pSY42RZJ2QDUWhdifZjNkWXpy4f4x4ueFGLZQ6pQRdI=,tag:P8ukKa8yLclyRjqHDwlz0Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7xXyjTH4Q7p8CDvGFPKo37im,iv:EMDM3fP23u8a/pIgVL1QJ6IlKKDMsN5FlLBKiLiqBK8=,tag:7Y7uK9sGXLELKLEMGsOxXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-01T02:01:46Z"
    mac: ENC[AES256_GCM,data:t6AMTsD7zgF4YmdTUnu4t3qujYvgkP9LYUJEDEmrZnbmFr7siVl+nnpT9t56QMqaDdKDgNLA73L1n7Ga7gxVdp96rnB26HlPhCjO/ZnhuzHSsCQh9a1wHC/UIQ6Uh3dm+EPXaDZKZqfpJ4cAnj/0AuCB4dA7XTkIghqmHc4hHAU=,iv:MEXJCQSKMU/Bca7ZRKTcrIDrzCSBxGgzWf7IizT6IgU=,tag:af0CosMaiHT5ktnrntstWg==,type:str]
    pgp:
        - created_at: "2021-10-29T06:33:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WARAAkaTnkVO+1eWJ/nJPx+yO2j07G7hoRw2hEe6k/F+raza9
            rikO6q1MiQPMVifu/uOQ7uMpe4H8cRRF/OKMgTQvHyB/GSr1iIOLLPWhtlUrnQyQ
            kXMpxqVw6IaAcB4QUjo863MLEFCmZL/jzuwq9iQYx70W2/t6jsv6Ex1736D3y0Dm
            Rt6twtkX/mDQ6iPkQobZ5UdM5Uok0nHpY+imuzzq3lSLJMAd1zQY5nCT6tv8PfbP
            ZDONHpyaloXJ5Wb0FEmKpSfR6PDLD4xxJE+cKoqO1UdJ3DkzWBFwzH/zPVVPHcpd
            kqX33SFuy/wwd1KEqKP6DyM4aLUCsE80rydQZk+1ywPhbXT61OR7OGRxZyzZsdqa
            L6RIcJSj0zWkcb0qmb3T26UjAo3RZI+u5zYZnKYsgF5L715vW0ow88SFTf3CRB9H
            A+NuHsKUFQxuc+Du7fawMyCnrDyl3Y8B0CaZycuRQrQC9655E+eSojnPbiNpiccQ
            /zAvnB7TDgTes/FfQKDTnTidl/zvMIT2OOFXov3nYZk+IVwcK2CI0hyN/GzzAhOn
            8HdAIqAfQQaCyfyI3O4dEeUWKva1kA5pl5bXE701dPjns2c1HqOkwp/b1I6rCktg
            dt3Zs+CmT/jX0l5Goyh7GyWrMJjd7KK0Nfth9W5rVAFLhdIZOaYfhnRmJv5b21nU
            aAEJAhD7w1jPpSJJAo9bXpDH8mD9RxlA6Ji6bgivdBcmh6EaOqB5sDbQwByipBsE
            cfipEgBobS89uE6QJMpofiuK/12BO9NUUYGei3NswGK+V/IFdzo+mH/kY8Vg+Vr8
            NaeR9HrTlB56
            =mbMt
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2021-10-29T06:33:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6AQ//SRLcGEe4wd3DxL1szKGRxwQ8FHy0MrSs9wDmA3vE5PGZ
            FxkneqdwrQNNNuwej3vXw47XlUDWB8ZJ1lTPK/jD6tRgZNj0js3SfeOsX/X72Ebi
            XGG1CjS02ReHkMJAoZvZBijIJ6hSz8udHB41EcBbOJ31x3SPihlK/+3eGWB8njLH
            WUUlZMIVmzUWnWCwDI190EIp4agokN6mPgRq9L7E3Q9oAub4/skbhuUy0YhmKjRg
            ald/Mf1OqqciPMgGFq6yXEZemsklasXP1mP4XE3HM9z/GXeAQ26R2GDwNPFX7Weo
            NUPXJZKwBymGgk0Toea63B27IRZ5g+1mzPXITAZ6cp2723pyJAsolcaO1uv+WATg
            lnnBmAoZfqRn9nkaA2hFOjG8LOv3u8/TN7HpCmSzJScZkV+HNHlv+dTOZZncwji0
            PTpPGiB0ppwZXFvx3Dq4q/gyQoskOvA9YVJWS2vPJb88bJIFOGeIf1WVdHZR36Ty
            TPtFzIBR8aeuVNH2uSVeT9PuhkoeJ/2ueQnWn+ZAG8IPfP09Axmzwvj316EeaEJX
            TKyefV5OIBPwv140BojwSDQVus3k9xSQr1cBL5h9rGKJJo4BDG8oK93gSfqxgIax
            XNU5joBJSDiz1t+C1hGm7GxN3Z5z0LSswr3kvuA/CM2Z59aPejUWKDat8i1lItXU
            aAEJAhDYkmBiVt8PiFFVRXAmgfnMqZq51gaaAUSENMOcDfwL+8VQuqQQMnfmMxUW
            mdgDo/dRq8JeNoTiaKXqonPS3aK+HzyvJngZqSZTkx8Kqr0rUADUl/TsiPoe/L6L
            NlCEHybRfDmW
            =1W1Q
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
