---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: omada-exporter
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: charlie-haley
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/charlie-haley/omada_exporter
      tag: "0.6.0"
    env:
      TZ: "${TIMEZONE}"
    omada:
      host: "https://${SVC_OMADA_ADDR}:8043"
      insecure: true
  valuesFrom:
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: site
      targetPath: config.value.omada.site
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: username
      targetPath: config.value.omada.username
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: password
      targetPath: config.value.omada.password
