---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: omada-exporter
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: charlie-haley
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/charlie-haley/omada_exporter
      tag: "0.6.0"
    env:
      TZ: "${TIMEZONE}"
    omada:
      host: "https://${SVC_OMADA_ADDR}:8043"
      insecure: true
    serviceMonitor:
      enabled: false # need to install prometheus-operator first
    ingress:
      enabled: true
      # ingressClassName: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "omada-exporter.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "omada-exporter.${SECRET_DOMAIN}"
          secretName: "omada-exporter-tls"
  valuesFrom:
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: site
      targetPath: config.value.omada.site
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: username
      targetPath: config.value.omada.username
    - kind: Secret
      name: omada-exporter-secrets
      valuesKey: password
      targetPath: config.value.omada.password
