---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - netdata
  ## need to install prometheus-operator first:
  # - omada-exporter
  ## Polaris is blocked on multi-arch images https://github.com/FairwindsOps/polaris/issues/284
  # - polaris
