---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 250M
    dashboard:
      replicaCount: 1
      ingress:
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          coredns.io/hostname: &host "goldilocks.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
        hosts:
          - host: *host
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: "goldilocks-tls"
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 100M
