---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.4
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 250M
    dashboard:
      replicaCount: 1
      ingress:
        ingressClassName: "nginx"
        annotations:
          # certs
          cert-manager.io/cluster-issuer: "letsencrypt-production"

          # Hostname
          coredns.io/hostname: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"

          ## public access via tunnel
          # external-dns.alpha.kubernetes.io/target: "homelab-tunnel.${SECRET_DOMAIN}"
          # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          # external-dns/is-public: "true"
          # TODO add basicauth or jwt for tunnel access

          ## Hajimari
          hajimari.io/enable: "true"
          hajimari.io/icon: "video-input-antenna"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-tls"
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 100M
