---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik-hub-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.traefik.io/hub
  timeout: 3m
