---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-relay
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: mvisonneau-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: "v1.24.0"
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "${CLUSTER_IP_RANGE},${RESERVED_LAN_CIDR}"
  valuesFrom:
    - kind: Secret
      name: tailscale-token-secret
      valuesKey: tailscale-token
      targetPath: config.authKey
