---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: tailscale-relay
      version: 0.0.10
      sourceRef:
        kind: HelmRepository
        name: mvisonneau-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: "v1.16.0"
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: 10.43.0.0/16
  valuesFrom:
    - kind: Secret
      name: tailscale-token-secret
      valuesKey: tailscale-token
      targetPath: config.authToken
