---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-relay
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: "v1.26.0"
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "${CLUSTER_IP_RANGE},${RESERVED_LAN_CIDR}"
    podAnnotations:
      secret.reloader.stakater.com/reload: "tailscale-token-secret"
  valuesFrom:
    - kind: Secret
      name: tailscale-token-secrets
      valuesKey: tailscale-token
      targetPath: config.authKey
