# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lab/g7JmwlCVrgGKghaExA==,iv:IV6RWuPCWCVxWkTHcqUdZqEY6tYcD7MGufV6DWNmKJA=,tag:BH4m9iWeEAh3Wx4To686uw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LG445n++aIKYen5KCpkPQHdq,iv:gnY/MDuFw5Sgr1BMXrq53nnTb7nM9oyCT7BkRf7UqoM=,tag:q6UIBbx3eJ8jr7djuA/h0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-29T06:28:44Z"
    mac: ENC[AES256_GCM,data:nIch2BhsDkLJYDlMKxtZKqaqEvr39OcDnTUpDvJx/zlk/xFrtSI4F6yxHNWhJ7D9gz6qqPUCinVjAe8NpdEsvCCVuwMF/Uhd6sNfNqQKVpR5j04K/HdKMcQLzfAftlmGLbp7bjdrhSOX3YpVr/hGcpS1bEsBpkXxC5LKJeiOjNw=,iv:f1BXAdI0riiNHu1LwyMbL5K+DN/UASwwiyWVW3DtAwU=,tag:37KW7dHHxUbFTvcm9LeyPw==,type:str]
    pgp:
        - created_at: "2021-10-29T06:28:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WAQ/9FAN1DhGAEmsVxv2DRRRU4GxkO5O/yo/rh9zuFgvAKQzw
            ralBySOPCqqULgQ6hcNZVUUDk7O1J5sGyBe/ohqNC1CrYyrNLr3VSjUzk4N0MVUz
            graaWSNCIkFVhjuw1SVu0sIqNM+KisJ1WdDIxsQGQV4tjhXSdZ/Qw5CHBSr2/P96
            BUzfF1xitUfhkeESymaBGOjOc/UWE726CLmI/6MrLzQInbk1S+1SrgexybMQSbqN
            8VFUerS+nicY6EuC3TFvJLnhBQ9TokOPH7jufVek7JxsiAfyc8Dq5LEXiU5h3ugA
            ysQZOPCG1wMjGhWsqp/wWNnOLGBPZmGOEJ01eT41uOpeGFWMX7sq9gDk3ZmlKrZW
            Bo4WkkynABm1i/nSVKOfqPiPFy4jWEdOZWh98rEdb8PdIZhrUt/SwJXAKSM8j8qY
            jL3iL3b55CBg9pFaWcc5WQ04p84J4o3cEKnaLurJCdpMRBuYhqVH44UUp6VXPjBV
            UbfsxY8GcfjmjsgxebOhdKm1SjzHZIstqvsbudLwlPdPubJujyo8XrLV1OOlObGe
            zRoTsrvT9pTpQz5UER7EDbu6n89mNLFyH4ISP9bezBsl0Z0LOHh9Y12atOUZXNUu
            SB0Bc6DhOeaxiA6EP/khvyCzNQ5RgXwdWZclxZea21dW0xSwb8P8t5YGEfX70vTU
            aAEJAhCQ0i57pi/PBKx9mtpekZHK3gh6Wq8oerFHjRXTPgnKpWcMWrNVwHlcO7dB
            57oSHIe2AjJpIkNiqMw9w9ywPCvx9MxA8zl7rhl1wph0aqdyAcrc02pNAR7Azo6o
            HiLtqv1SDtol
            =ioTU
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2021-10-29T06:28:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6AQ//clFFSJLzhPuGNXlJZ1YcJwadkpqV1B+Oqq/RaasVLlQc
            x6H3Hic1FpZdvogp9WeDisaiKaAiIzqeDnlFniHyinY95KnlQxczgRkgzPFH8bO2
            miD01/IBmPxqROadx5Xszv3Ft/PnoqfaUrHBHB/aMZsU8uuc4jqOk3/EBr/GwkL+
            3v2k4N/+cZZGUD9gnDdgtflNnz0lcce0DEt011CT0IBKQYi8fmtCTABeEpODxjF6
            xY1brmdBbKD/KfmER/GaA68g7L7GMb1w/5qzlN4zjpf4cM5rUQ8F4hUND/+BlYEG
            +kNIsnowWtWGokG/H78uFTL6J2uLIQmvZya5LwehmORSiGb3APLVz9Qa1+69w4QM
            6CriizWU0qtAmwIPlKWH1lQ1qm+ujzJc1dRrY9q55CccD2PQDplKMt5KspbNofVc
            sLZfiWxE/ZntvMeF6J46wH+5PW2vUwj9KAVeV9uQR69abZY9Xj6DKfKgevPxVrqF
            qMwIa6mTl/lzllNWdg4XMN/FTbltwVN7ZgbauZEwNNMPmvsQLqUq9nweKLXW1wvd
            A+c6gdNmwMwNDx5Cxp73zhMLEjxpdY3WzWB3XghI0zmKcx6ep4Of4xiRCMwUn4bP
            2YX0MBOaf/59YsgdozZenAvfImCDSoxShjqEQWnlxUyjJjXHmti9eqh/mvR8YcPU
            aAEJAhAXyzPAsopTjLWBG2gvcas8o4bGyMRpXkZG+Xd26DCg5PXPZ783B7q5SfeY
            gf7JiC1/NTGwzMauFWEd7jKpZsST87pK9DFIzk7gFw4cFwTPrsOAFzA/l1W9prN8
            o1HuW+ER4+Iu
            =n4hE
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
