---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: omada-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/omada-controller
      tag: 4.4
    env:
      TZ: "America/Los_Angeles"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-automation"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "omada.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "omada.${SECRET_DOMAIN}"
            secretName: "omada-controller-tls"
    persistence:
      config:
        enabled: true
        existingClaim: omada-controller-config
        subPath: data
    podAnnotations:
      configmap.reloader.stakater.com/reload: "omada-controller-config"
