---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: omada-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: mbentley/omada-controller
      tag: "4.4"
    env:
      TZ: "America/Los_Angeles"
      MANAGE_HTTP_PORT: 8088
      MANAGE_HTTPS_PORT: 8043
      PORTAL_HTTP_PORT: 8088
      PORTAL_HTTPS_PORT: 8843
      SHOW_SERVER_LOGS: true
      SHOW_MONGODB_LOGS: true
    hostNetwork: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "router-wireless-settings"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: home-omada-redirect@kubernetescrd,home-omada-headers@kubernetescrd
        hosts:
          - host: "omada.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "omada.${SECRET_DOMAIN}"
            secretName: "omada-controller-tls"
    service:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: https
      controller:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_OMADA_ADDR}"
        externalTrafficPolicy: Local
        ports:
          # see https://community.tp-link.com/en/business/kb/detail/362
          mgmt-8088-tcp:
            enabled: true
            port: 8088
            protocol: TCP
            targetPort: 8088
          mgmt-8043-tcp:
            enabled: true
            port: 8043
            protocol: TCP
            targetPort: 8043
          portal-8843-tcp:
            enabled: true
            port: 8843
            protocol: TCP
            targetPort: 8843
          eap-discovery:
            enabled: true
            port: 29810
            protocol: UDP
            targetPort: 29810
          eap-management:
            enabled: true
            port: 29811
            protocol: TCP
            targetPort: 29811
          eap-adoption:
            enabled: true
            port: 29812
            protocol: TCP
            targetPort: 29812
          eap-upgrading:
            enabled: true
            port: 29813
            protocol: TCP
            targetPort: 29813
          init-check:
            enabled: true
            port: 27001
            protocol: UDP
            targetPort: 27001
          init-info:
            enabled: true
            port: 27002
            protocol: TCP
            targetPort: 27002
          db-access-old:
            enabled: true
            port: 27017
            protocol: TCP
            targetPort: 27017
          db-access-new:
            enabled: true
            port: 27217
            protocol: TCP
            targetPort: 27217
    persistence:
      data:
        enabled: true
        mountPath: /opt/tplink/EAPController/data
        existingClaim: omada-data-pvc
      work:
        enabled: true
        mountPath: /opt/tplink/EAPController/work
        existingClaim: omada-work-pvc
      logs:
        enabled: true
        mountPath: /opt/tplink/EAPController/logs
        existingClaim: omada-logs-pvc
      cert:
        enabled: true
        mountPath: /cert
        type: custom
        volumeSpec:
          secret:
            secretName: omada-controller-tls

    resources:
      requests:
        memory: 1200M
        cpu: 1200m
      limits:
        memory: 1500M
