---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-work-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
