---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: scrypted
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/koush/scrypted
      tag: v0.0.171
    env:
      TZ: "America/Los_Angeles"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "scrypted.${SECRET_DOMAIN}"
            paths:
              - "/"
        tls:
          - secretName: scrypted-tls
            hosts:
              - "scrypted.${SECRET_DOMAIN}"
    service:
      main:
        enabled: true
        ports:
          http:
            primary: false
          https:
            enabled: true
            primary: true
    persistence:
      config:
        enabled: true
        existingClaim: scrypted-config
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
