---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scrypted
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: scrypted
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: koush/scrypted
      tag: v0.1.14
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        enabled: true
        ports:
          http:
            primary: false
          https:
            enabled: true
            primary: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          coredns.io/hostname: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "{{ .Release.Name }}-tls"
    persistence:
      config:
        enabled: true
        existingClaim: scrypted-config
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
