---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ring-mqtt-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1000Mi
