---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ring-mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: tsightler/ring-mqtt
      tag: 5.0.2
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 55123
            protocol: TCP
            targetPort: 55123
          rtsp:
            enabled: true
            port: 8554
            protocol: TCP
            targetPort: 8554
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "doorbell-video"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "ringmqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ringmqtt-tls
            hosts:
              - "ringmqtt.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: ring-mqtt-pvc
        subpath: data
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    addons:
      codeserver:
        enabled: true
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "true"
            hajimari.io/icon: "doorbell-video"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hosts:
            - host: "ringmqtt-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "ringmqtt-config.${SECRET_DOMAIN}"
              secretName: "ringmqtt-config-tls"
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 750Mi
