# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_TOKEN: ${BOOTSTRAP_CLOUDFLARE_TOKEN}
    CLOUDFLARE_RECORD_NAME: ipv4.${BOOTSTRAP_CLOUDFLARE_DOMAIN}
