---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 10.24.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  dependsOn:
    - name: cert-manager
      namespace: kube-system
    - name: metallb
      namespace: networking
  values:
    image:
      name: traefik
      tag: 2.6.1
      pullPolicy: IfNotPresent
    deployment:
      kind: Deployment
      replicas: 1
      podAnnotations:
        reloader.stakater.com/auto: "true"
      additionalContainers:
        - name: cloudflared
          image: raspbernetes/cloudflared:2022.6.3
          args:
            - tunnel
            # Points cloudflared to the config file, which configures what
            # cloudflared will actually do. This file is created by a ConfigMap
            # below.
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: cloudflared-credentials
              mountPath: /etc/cloudflared/creds
              readOnly: true
      additionalVolumes:
        - name: cloudflared-credentials
          secret:
            secretName: cloudflared-credentials
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
            items:
              - key: config.yaml
                path: config.yaml
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: traefik-svc
        metallb.universe.tf/loadBalancerIPs: |-
          ${SVC_TRAEFIK_ADDR}
      spec:
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_ADDR}"
      - "--providers.kubernetesingress.ingressendpoint.hostname=homelab-tunnel.${SECRET_DOMAIN}"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
        # Enable HTTP/3. Requires enabling experimental http3 feature and tls.
        http3: true
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    experimental:
      http3:
        enabled: true
      plugins:
        enabled: true
    metrics:
      prometheus:
        addRouterLabels: true
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: "traefik-secrets"
