apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - cloudflared-config
  - middlewares
  - dashboard
  - tls-store
  - default-tls-options
  - helm-release.yaml
