apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - default
  - flux-system
  - home
  - kube-system
  - kubernetes-dashboard
  - metallb-system
  - monitoring
  - networking
  - system-upgrade
