# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B5T1nWn1H2SbqDwl6qV9bZP7x46tTtd5medHixyBW6XeLzmrUODLsg==,iv:wsBTbSslo5LY5g7W9PmPUP2/zCVrVXokaVgf+N8DqUI=,tag:3hE9k66E5wPy0TkigtHcSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-01T20:09:10Z"
    mac: ENC[AES256_GCM,data:lasIrOWxgiJjwFb56DJx/7ScOvyMpnNfNRZDiUhDmX6TMmSp9Xqt5tqsPBGVMWe5XBYuUeIT5XgEoPLtLLzqUbweDWXDOdlR9Z0tR1oympAByH9Q0OoO1hsx/tDotSC0vc0uFLELQXzfJzmotcY2Jk+UkrYC+2j0kW+Xv3hnjSs=,iv:df9plyFgBe41wLKWZ1v9cfa0KZD+5i0CFg3dc+TvQ+U=,tag:GDD/k6pb7zFATmVa/g8n2g==,type:str]
    pgp:
        - created_at: "2022-07-01T20:09:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WARAAieG/7RmxplofsGeEOXkLCfyjKx4JR+z4sCE41lyXjGbY
            blaz7duc530KnZjtysKhpeItCXNhlnEyLqYSk1gMWE+sabXNe3xkgTL2crLiQa1S
            PTDnf8ycoYEonD146EC/znO7hBTR6TvaUmjopkVtyYVdrNqeLMvAksdawIiyvbMp
            esnri0zfGVHc5EB1VxeruOOhjBYr3bYunZ7Vn3NUAZy3PfNL8CMRKklvFE9hWUil
            RJuGd/a4K8gR5Lox4xiUg82Z3ro05EGhPWrWUSAPpuD2iFvMtPIhGdkFgwyplve/
            rJFOOla4RwLJ0pMqm6E1fPp6BkD6+rgaCVb0dl9UIvLydm7CpTfXYwG0IR1H9R+n
            LziRw/p+M7oLIInRtKVAXKxbeGR3LmmWjR9RcgZFgDQecA0blR1P7j0cS3DFycGx
            XGHplcrJOqlDw4cmij6y1tFZ7ER/YPRLmByxjYnJU2Cxm/p1kx4ftVuUsA4KH5F2
            tZ9kjOSLMj8nDIzhfS8hyYrwOvG4PaW9sOrT1PXW1rSvf8BlDxlowo0SZrRRSUF0
            N8MrAwNnBnCK/hGHIr3RkcFMrZ1FO1ZSN/WW4miBCTiB+M5VrhoKDh73seevq4bi
            1G3A2DBKHWOeUq+Zk4Wz8FAv1qBx2wqcGVKPVpnQKnI4T9thBlIGA6hU2McftIfU
            aAEJAhDSQkeQmtDIxWmyVr7aq8cqIdmDK9kONpDViGNWg5BCgmfmQmj1mqc5sxBJ
            /OkbJ9D+EpndE9GgzxTgNmRwJVt9+Au2fvAdoUqAhFr26z7cIVeVJqjiCcm7Cj3B
            QaqdLWRgH7Lg
            =Pfv+
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2022-07-01T20:09:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6ARAAk9g0lJLcmOvIIGWX4o1LxpwylhumDDQmFQnsqViYJeIH
            q4JHCZDGde5d81qBWWmQP9ATSQZCMDQ+uKfgFqkSXg5bzgoP8EGARL5fOHiVe9ZF
            mVVmM/tfhGN7bMHnHx4aL8kQX4ZVjbXRjuzcHkA/BWpm9zPGu0HmluHm10Gfzga+
            AN2niKjcN3c0rrIXtSFcQvMFEEwLy6hvEz8tPGtbO4hbt7TEUdOG/pP8A8ph7SN1
            X0GEFUkqlA89SHC1fRJyJNlkvvhSpd9qThr/4XBkTHC8T/TdJ17rhR9Vdjh0+ZB3
            yv26bcAYuUvfrRS7y8DrxZvAi7tfsKIYWM3qmdhaqQrdWUuC8sSB8c3NLW7KiexE
            kzBsUUMdkMbTqK+txeoVBfmElTKR5l6MbVtHGxy+33nJW2bX80excWdSujOVbGhZ
            HEJzxksEtDqXv1/rC8tJow3yir23nJVbs0l1TG0h4WwDXsy0LAHnkOO6ochB9IHU
            P9PPNhqUX23GcosN6UkDWgLMq6YM24FCUZmAV35fkwIUBJEuzkUvnLvBlDpUA8BP
            lJhHuIB6iqLfMY4iRYWImx5Y3fD37NusZCAR4ukQ4YRs0NFxgVoZeJmksmLfNs2O
            bdHMfkRdaPJPxfzkPkb8SW65tU8pAB2XMj21tNeMFKdtApNdXJfevZoxeiC6ItjU
            aAEJAhCTyXymFtlwHEnG/twRyHVWukdGahNG3uur5xmWWxjb62hu2cE9EDlEPIxs
            kMs8cGS2ZB30XXaBe75TQGgx45EUJkLcx88wd3OBb6o6xD8YrHRii60a0zfXxay9
            uI9CqGhypTU2
            =U9WE
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
