# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:NnijtogF8d8T12w1J6PNoYHJqYSpmJiZiXrwrxHJu/53wqsuOxLpcw==,iv:SBk5R5OEDQtGXfCuolt1k1kZMa+iSLK6/105JIV0KNQ=,tag:8Uj7Zix+uJ3b/P4kalgTkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-10T22:29:03Z"
    mac: ENC[AES256_GCM,data:T2vxGO/nB9BCj9xCoKwUULXcSZLl9jmh0mmR4wYdGnXayCRKkhDtMNMJiF4q62cCZDzx8YFqYDOe0VIWUmvuMaSRnrvw6JuOYTFLg4LWuhe9ooF9ERkT/Tn0nb42H1jG8pCYY/bRu/FPYlFZT0EqQndjQ8kQhuRE4uSBK4KDmKA=,iv:DiMyHSfcUI/NF3ylw81J6Jc2n48I2eF1wCqxGZV9Mh8=,tag:o885Z+cZ4pD4S1XXFGtn6w==,type:str]
    pgp:
        - created_at: "2021-09-10T22:29:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxvSZKBJ361WARAAjUGgryCSgxtiMdxfVa2wO8jvuf18qBXQaKT9QK3gunDD
            TLPi1xVU+iH3bwTgFGRtciHvlbl73BQWxyBTP3cgN3f+SNvSi/d87Ex3AN+QaReZ
            GUXX848KxAmwcTge8P2YghQeFlee+8qy+u3dJKyS5s5K5tgfxwvFBrll5OBuAExQ
            pMEfMRKiQq4e8XqzNMur4lrMbxw9Cv1GtH4/+ArNZdyLf4WNGPAspCfRvk/vRxc4
            OJBOEo3CMTIiU4jQiHA6ch2A6JpytIB4hkwfMIc6J+2BF5O2Z12IvfZoV3QuI3Vm
            pN1syI85D1qrqfJdSsxB22QvcHE/UvWVTxmfXcr6VKPhy/sQzSDEyJksl6kdj8E9
            XDXIrl7PeFHrV5CALqtDt3Tv9vk2s5yrPcxN4DmYN3+cQnqJDRxZ8VcVtDRcJsWz
            GqD8k6EbG+biURRarQrpdjr9UAxJSF16Tb8N2OzxxbYaBcToVzZnbQfoGxXMRbA+
            Je7ZudnxOwvYwmT0p6mEgLe1n8XHLl8YI9j4MdV4d0T8HqGwgIliWiV4cjk6CgSs
            M/XtO23WBxxGSfwvpPXnhkzKXOpI5xIv9RnwFW1SpxKmALcPqB+lz6v4qljm0HB+
            5dQ0xX6CMpUZ2aMfNzFqzIolsQYYw2S1rISMIXYIVnv81PwRfW4B1zkpTzPWdPbU
            aAEJAhVtGuadrmRYih3TMxv23xbbHCWg/eqP/Jqg5/cvBIGj/V0h4ZUNEYEbTXpg
            TDkXWQXv7zKSG6Jv3UPi32qPInmkuGSe7NV/PNNfpUBKnSh1sH03VWP/3/MFqZK7
            hpH6YjnFFaZ/
            =m3d3
            -----END PGP MESSAGE-----
          fp: 4D213A396707000311C6E8F30BF09899BFF16C22
        - created_at: "2021-09-10T22:29:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8PLKb7USqY6ARAAhfXgKH2oSHk42PHpoPkk9POSxindTXPAezgOPkm6ffrn
            Nf43Xd1Ry9Pxe09zQQtbP677hUnd0kkfaR+05uEvcJo0ue0FT2GgJlhrF6WfXLDw
            t94kL+1neBsug/u+6X0h+Wfr8jKVPueBbfwouteMsUFyK1YRYGmKzBQZ0DC1Y2CB
            NgIYDgIbfO+yPPQENIyUXAqi01/k8f5/Ee2c4bJqGuaF27L/xhNoSTsvMOm+Bbmn
            v+MlMZeeOT1kR39zCxuiPjc6wY7e6DvmXUfmysvCyq2PyzhE/L+sG9wFYoBa+ZCC
            giZiXKDOaGlYfuBwvHjfbX7Sg/B5/Uc4GwPY7min8liyYbC8DgKmXssYM0Ci0aoU
            xRDO8P4CMUA+LvH+emClR+8hcSdni9RpiQfSsalWttkub83bfDthnRFxxNGFoXGs
            7A68cuGvxtnA4NkleAnDKHTxMXnkAYk3RH5X2g4QdgebXX1WeSW9dLEvoluBlZc9
            yJhV0pyPhzJJ/EWz9HjiItZETQTq3Pmhuo+QTNhdOOjuWbJrcbslxu4/99CJ0CBN
            l4VGUhP3HX0/l9z9NUY4vbiHN3C8WJ/NHDfDNc3nh2uM9snfBtxS1KTwBMe/Wx1Q
            pQfOz4Mb5DJ51d98zw0dcTmPkDfxlpNyuS/h8+axSFzAa5zhRBAkuNRlyAkrT/PU
            aAEJAhU8/5I9PPoBwGAESrg+meoOWZyXtPJhps589R/t+lgeZZSUs55R6QgKy18J
            g1KhXlgi0U1V2fDDHRNiw0kj0GItRznRZdI22PPWhRLYAvstcJQ16kcgC8biuQbs
            FZ/iPaRULJ0C
            =f6RH
            -----END PGP MESSAGE-----
          fp: 0F022C1EE9A89492656E7933014A0F89EBCEB9F4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
