---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 5m
  releaseName: netdata
  chart:
    spec:
      chart: netdata
      version: 3.7.19
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: netdata/netdata
      tag: "1.35.1"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: ""
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      spec:
        ingressClassName: "traefik"
      hosts:
        - host: "netdata.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "netdata.${SECRET_DOMAIN}"
          secretName: "netdata-tls"
    env:
      TZ: "${TIMEZONE}"
    parent:
      claiming:
        enabled: true
        token:
        rooms:
    child:
      claiming:
        enabled: true
        token:
        rooms:
  valuesFrom:
    - kind: Secret
      name: netdata-secrets
      valuesKey: parentToken
      targetPath: parent.claiming.token
    - kind: Secret
      name: netdata-secrets
      valuesKey: childToken
      targetPath: child.claiming.token
