---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 15m
  releaseName: netdata
  chart:
    spec:
      chart: netdata
      version: 3.7.22
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: netdata/netdata
      tag: "1.35.1"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: ""
      hosts:
        - "netdata.k8s.local"
        - "netdata.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "netdata.${SECRET_DOMAIN}"
          secretName: "netdata-tls"
      spec:
        ingressClassName: "nginx"
    env:
      TZ: "${TIMEZONE}"
    parent:
      claiming:
        enabled: true
        token:
        rooms:
    child:
      claiming:
        enabled: true
        token:
        rooms:
  valuesFrom:
    - kind: Secret
      name: netdata-secrets
      valuesKey: parentToken
      targetPath: parent.claiming.token
    - kind: Secret
      name: netdata-secrets
      valuesKey: childToken
      targetPath: child.claiming.token
