---
name: Schedule - Update Flux

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  flux-upgrade:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          fetch-depth: 1

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Upgrade Flux
        id: upgrade
        run: |
          CLI_VERSION="$(flux -v)"
          VERSION="v${CLI_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --network-policy=false \
            --export > ./cluster/base/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"

      - name: Create pull request for Flux upgrade
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e # renovate: tag=v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "flux/upgrade-${{ steps.upgrade.outputs.flux_version }}"
          delete-branch: true
          title: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          signoff: false
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: "chore(deps): upgrade flux components to ${{ steps.upgrade.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.upgrade.outputs.flux_version }}
          labels: flux/upgrade
