---
name: Lint YAML files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: "**.yaml"
              - added|modified: "**.yml"
      - name: Lint files
        if: ${{ steps.filter.outputs.yaml == 'true' }}
        uses: reviewdog/action-yamllint@aabd7aef24430a8da23122ca6711faec445dfcf6 # renovate: tag=v1
        with:
          yamllint_flags: "-c .github/lint/.yamllint.yaml ${{ steps.filter.outputs.yaml_files }}"
