---
name: Lint Markdown files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: "**.md"
      - name: Lint files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: reviewdog/action-shellcheck@1ca1ab3612f22b3b3dbebac53540ee8e44dd8eb6 # renovate: tag=v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          markdownlint_flags: "-c '.github/lint/.markdownlint.yaml' ${{ steps.filter.outputs.markdown_files }}"
