apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - home.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - kubernetes-dashboard.yaml
  - networking.yaml
  - system-upgrade.yaml
